appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kF/CDBlakKeBQxLjFIDlWmIoe59xIW2Z7WW8c8+bP859Yic0zSqUjPd3Ug+tpx8UJbswd0C6LfxWmavuO0QUaC5ex7LuklhJcxyz/0tfzqoSxsGUAwhsQIh/4b58uW/wXi3L82UrtO4jtwiLPXX0uDN/OkxS0cEPzTdY/JM6bdyp1LYnp7/Hp5e/bRymo2Gu/BdG+X1zaxxHHkTdbyi581r8zuvJEiLB0/0w8MS0eFrCy/tavq1E+H+hsetuV0tbbcKnmvEd4fOpiCdGPUdg10tWB15lxILJUR7/TiIhMlJLh3dBB3WWRu+j8YTRZycsEooXuYjU7YOJ4EK7xgwmqBlF9ocg76v4SjdxJoUvutVwzuEPFQfTotO/Qwi3xLx/s4qGb1zEuq1VvAEEs61+SqalMRwL4xSfyo6NKoHOOR7uHpQqOuQXeftmhzr7Ob9JMQDnURX1pL2TWplByx9fQtWvcj6bz/Sk3JnGtVNKOUG4X0VOsaTqxHr8S25d83Ya1NAZf+WaFfSWFKsxPcVaDiY90XpiiHaWJQy/LbawaxXJAh4xpczxl00F26D7bhPdXfZlM+yctc6WzZc467pQzxKS44XfdVc2DwzZLyJLIaGfJl4POx1CSYlpPYw5wE/WU0JKdvN3r+PAg9V/FWjVNct8xVucXyMN9yD5GC2DtJ4=}
