travis:
  secure:
    BINSTAR_TOKEN: K1+5cAHhTU0Y6tj0dzyl6cKYQUIbxg4mvYnF6gIG/IJeavfeQfj5eTzmN/tcu3VBcyrt55ly9qOBRD7TQEo4oVx0zlZeKYyWSOwkPi/86NEQRkwIdxyuqGnF0n7gUAT/K+ZLyU47nWoU9W3o0QBAEmoxx1H6fXl4+yJwI58Cb0HjF9WGFgizodUNvwuUqptBsZEBcYErDQ3E4+M4qj+/u3sY07UTvUFzxO65Tf459iku077+M5733OD6yN5aIMKk+LvxM9E1eKNyECXEowHYs0PCHE1d82f6ALy5F8KfS/b5OM1P1U9Pa/vkFgH5IE5E4JsvBU+u4qer06FOs3BNOJ6XP/GO6lVi2ALRuICqfQHcNAjuY1Ed3T6HkVl7j67xeNREvjWArdTZ7Ji+XbmNbjZJNinJxYO1ped5z84577y20dy9o25smERX/ggR3qtfXQbyhkWEzvUTntTE6abLKznbhvrlk2ewdruvYKfEVI/EtzT8qc0u7vSQrJILMsU6/qs/qnRndp+RxQYxPfCpVbDf0gG4HF/OGlr0wXJBg0Z2fEgZHRsoCwNm4bedwR0wSwMCal6RA7TrwXQzF3gq2xkoztxSutD1IGj3svDbrRmKSs2ao0pN9nz/UCKcrVvd6XVJUHCNkb+DHq3b1L1pg2QZUm8bBP/LX2uhRQdDCu8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
